name: First Workflow

on:
    workflow_dispatch:
    issues:
        types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, GitHub Actions!"

  job1:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1
      run: echo "Step 1 complete!"

    - name: Step 2
      run: echo "Step 2 complete!"
  
  job2:
    runs-on: ubuntu-latest
    needs: job1 # Ensure job2 waits for job1 to complete


    steps:
    - name: Cowsays Action
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: "Ready for prod–ship it!"
        color: magenta